"""Explainable GEE ↔ OGE conversion core based on rules and operator mappings."""

from __future__ import annotations

import re
from typing import Dict, List

from .analysis import analyze_gee, extract_gee_apis
from .mapping import MappingLibrary


def _oge_call(name: str, operands: str = '...') -> str:
    return f'service.getProcess("{name}").execute({operands})'


def convert_gee_to_oge(gee_code: str, library: MappingLibrary) -> Dict[str, object]:
    """Analyze GEE and generate an OGE skeleton with mappings and completion points."""
    analysis = analyze_gee(gee_code)
    report = library.match_report(analysis['apis'])
    lines: List[str] = [
        '# Generated by GEE-OGE core converter', 'import oge', '',
        'oge.initialize()', 'service = oge.Service()', '',
    ]
    for step in analysis['steps']:
        lines.append(f"# --- {step['description']} ---")
        for normalized in extract_gee_apis(step['code'], analysis['variable_types']):
            mapping = library.find_gee(normalized)
            if mapping is None:
                lines.append(f'# TODO: no mapping for {normalized}')
            elif mapping.mapping_type == 'one_to_many':
                lines.append(f'# {normalized}: composite implementation')
                lines.extend(f'result = {_oge_call(oge_api)}' for oge_api in mapping.oge_apis)
            elif mapping.mapping_type == 'native_python':
                lines.append(f'# {normalized}: use a native Python implementation ({mapping.note})')
            else:
                lines.append(f'result = {_oge_call(mapping.oge_apis[0])}')
        lines.append('')
    return {'code': '\n'.join(lines), 'analysis': analysis, 'match_report': report}


def convert_oge_to_gee(oge_code: str, library: MappingLibrary) -> Dict[str, object]:
    """Scan OGE getProcess calls and create a semantic-preserving GEE conversion draft."""
    process_names = re.findall(r'getProcess\(["\']([^"\']+)["\']\)', oge_code)
    lines = ['// Generated by GEE-OGE core converter', '// Complete data source and parameters before running.', '']
    missing: List[str] = []
    for process in process_names:
        reverse = library.find_oge(process)
        if not reverse:
            missing.append(process)
            lines.append(f'// TODO: no GEE mapping for OGE process {process}')
            continue
        gee_names = ', '.join(item.gee_api for item in reverse)
        lines.append(f'// OGE {process} -> {gee_names}')
        lines.append(f'// Replace with the corresponding GEE call: {gee_names}')
    return {'code': '\n'.join(lines), 'oge_processes': process_names, 'missing_processes': missing}
